import React from 'react';
import { Target, Lightbulb, TrendingUp, Layers } from 'lucide-react';

export const AboutPage = () => {
  return (
    <div className="min-h-screen bg-[#030712] p-8 pb-32 flex justify-center items-start">
      <div className="max-w-4xl w-full space-y-10">
        
        <header className="text-center py-10 border-b border-[rgba(255,255,255,0.05)]">
          <h1 className="text-5xl font-black text-white tracking-tighter mb-4">
            ResQNet <span className="text-blue-500">AI</span>
          </h1>
          <p className="text-gray-400 text-xl font-light">Autonomous Multi-Agent Disaster Response Platform</p>
        </header>

        {/* Problem Statement */}
        <section className="bg-[#0B0F19] rounded-2xl p-8 border border-[rgba(255,255,255,0.05)]">
          <div className="flex items-center mb-6">
            <div className="w-12 h-12 bg-red-500/10 rounded-xl flex items-center justify-center mr-4">
              <Target className="text-red-500" size={24} />
            </div>
            <h2 className="text-2xl font-bold text-white">The Problem</h2>
          </div>
          <p className="text-gray-300 leading-relaxed text-lg">
            During large-scale disasters (earthquakes, floods, wildfires), emergency hotlines are overwhelmed. 
            Responders lack real-time situational awareness, and crucial seconds are lost manually verifying fake SOS alerts, coordinating supply logistics, and routing ambulances around destroyed infrastructure.
          </p>
        </section>

        {/* The Solution */}
        <section className="bg-[#0B0F19] rounded-2xl p-8 border border-[rgba(255,255,255,0.05)]">
          <div className="flex items-center mb-6">
            <div className="w-12 h-12 bg-green-500/10 rounded-xl flex items-center justify-center mr-4">
              <Lightbulb className="text-green-500" size={24} />
            </div>
            <h2 className="text-2xl font-bold text-white">Our Solution</h2>
          </div>
          <p className="text-gray-300 leading-relaxed text-lg mb-6">
            ResQNet AI replaces manual coordination with a highly specialized hive of 6 autonomous AI Agents powered by Google Gemini.
          </p>
          <ul className="space-y-4 text-gray-300">
            <li className="flex items-start">
              <span className="w-2 h-2 mt-2 mr-3 bg-blue-500 rounded-full flex-shrink-0"></span>
              <span><strong>Instant Triage:</strong> The Commander Agent analyzes SOS requests in milliseconds.</span>
            </li>
            <li className="flex items-start">
              <span className="w-2 h-2 mt-2 mr-3 bg-blue-500 rounded-full flex-shrink-0"></span>
              <span><strong>Verification against APIs:</strong> The Intelligence Agent cross-references the SOS against live USGS / Open-Meteo data to filter fake reports.</span>
            </li>
            <li className="flex items-start">
              <span className="w-2 h-2 mt-2 mr-3 bg-blue-500 rounded-full flex-shrink-0"></span>
              <span><strong>Automated Dispatch:</strong> The Rescue & Resource agents simultaneously calculate OSRM routes and dispatch the nearest available responders and supplies via WebSockets.</span>
            </li>
          </ul>
        </section>

        {/* Future Scope */}
        <section className="bg-[#0B0F19] rounded-2xl p-8 border border-[rgba(255,255,255,0.05)]">
          <div className="flex items-center mb-6">
            <div className="w-12 h-12 bg-purple-500/10 rounded-xl flex items-center justify-center mr-4">
              <TrendingUp className="text-purple-500" size={24} />
            </div>
            <h2 className="text-2xl font-bold text-white">Future Scope</h2>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="bg-[#141C2D] p-5 rounded-lg">
              <h3 className="text-white font-bold mb-2">Drone Integration</h3>
              <p className="text-sm text-gray-400">Deploy automated recon drones based on coordinates generated by the Intelligence Agent.</p>
            </div>
            <div className="bg-[#141C2D] p-5 rounded-lg">
              <h3 className="text-white font-bold mb-2">Predictive Evacuations</h3>
              <p className="text-sm text-gray-400">Use historical data to autonomously ping citizens to evacuate before a flood or wildfire breaches their zone.</p>
            </div>
          </div>
        </section>

      </div>
    </div>
  );
};
